#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Ocelot+K8s/OYan.Order/OYan.Order.csproj", "Ocelot+K8s/OYan.Order/"]
COPY ["OYan.Core/OYan.Core.csproj", "OYan.Core/"]
RUN dotnet restore "Ocelot+K8s/OYan.Order/OYan.Order.csproj"
COPY . .
WORKDIR "/src/Ocelot+K8s/OYan.Order"
RUN dotnet build "OYan.Order.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "OYan.Order.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OYan.Order.dll"]