#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Ocelot+Consul/OYan.Store/OYan.Store.csproj", "Ocelot+Consul/OYan.Store/"]
COPY ["OYan.Core/OYan.Core.csproj", "OYan.Core/"]
RUN dotnet restore "Ocelot+Consul/OYan.Store/OYan.Store.csproj"
COPY . .
WORKDIR "/src/Ocelot+Consul/OYan.Store"
RUN dotnet build "OYan.Store.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "OYan.Store.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OYan.Store.dll"]